/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        // Extended colors from design system
        cream: '#F5F2EC',
        'cream-dark': '#EDE9DF',
        'cream-hover': '#E8E3D9',
        'warm-white': '#FAFAF8',
        surface: '#FAFAF8',
        elevated: '#ffffff',
        subtle: 'rgba(26,26,24,0.08)',
        charcoal: '#1A1A18',
        'charcoal-80': 'rgba(26,26,24,0.80)',
        'charcoal-60': 'rgba(26,26,24,0.60)',
        'charcoal-30': 'rgba(26,26,24,0.30)',
        'charcoal-10': 'rgba(26,26,24,0.08)',
        sage: '#8FAF8A',
        'sage-dark': '#5a8a55',
        'sage-light': '#C8DBC5',
        'sage-pale': '#E8F0E7',
        terracotta: '#C8714A',
        'terracotta-dark': '#a85a36',
        'terracotta-light': '#E8A98C',
        'terracotta-pale': '#F5E4DB',
        gold: '#C4A862',
        'gold-dark': '#a08030',
        'gold-pale': '#F0E8D4',
        blue: '#5B82A6',
        'blue-pale': '#EAF0F6',
        purple: '#8B6FAF',
        'purple-pale': '#F0ECF8',
        red: '#C85A5A',
        'red-pale': '#F8ECEC',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xs: 'var(--radius-xs)',
      },
      fontFamily: {
        sans: ['var(--font-body)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'Fira Code', 'monospace'],
      },
      spacing: {
        1: 'var(--sp-1)',
        2: 'var(--sp-2)',
        3: 'var(--sp-3)',
        4: 'var(--sp-4)',
        5: 'var(--sp-5)',
        6: 'var(--sp-6)',
        8: 'var(--sp-8)',
        10: 'var(--sp-10)',
        12: 'var(--sp-12)',
        16: 'var(--sp-16)',
        20: 'var(--sp-20)',
      },
      fontSize: {
        '4xl': 'var(--text-4xl)',
        '3xl': 'var(--text-3xl)',
        '2xl': 'var(--text-2xl)',
        xl: 'var(--text-xl)',
        lg: 'var(--text-lg)',
        md: 'var(--text-md)',
        base: 'var(--text-base)',
        sm: 'var(--text-sm)',
        xs: 'var(--text-xs)',
        xxs: 'var(--text-xxs)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        sidebar: 'var(--z-sidebar)',
        topbar: 'var(--z-topbar)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
      },
    },
  },
  plugins: [],
}
